name: Auto Version Branch Workflow
on:
  pull_request:
    types: [closed]
    branches:
      - 'v?[0-9]+.[0-9]+'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-sandbox-common.yml@main
    with:
      needs_build: true
      install_command: "npm ci"
      build_command": "npm run build-clean"
      cloud_deploy: false
      skip_deploy: true
      update_version: false
      needs_docker: false
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      BUILD_ARGS: ''
