name: Deploy to Garden
on: workflow_dispatch
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-sandbox-common.yml@main
    with:
      needs_build: true
      needs_docker: false
      install_command: "npm ci"
      build_command: "npm run build-dist"
      cloud_deploy: false
      skip_deploy: true
      update_version: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      BUILD_ARGS: ''
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GH_GCP_TOKEN: ${{ secrets.GH_GCP_TOKEN }}
